version: '3.8'
services:
    server:
        image: server
        build: .
        container_name: server
        ports:
            - 8001:8001
    gateway:
        image: nginx:alpine
        container_name: gateway
        restart: unless-stopped
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .blobs/gateway/gateway-cert:/etc/ssl/gateway-cert.pem
            - .blobs/root-ca/root-ca-cert:/etc/ssl/airbotics-root-ca-cert.pem
            - .keys/gateway-private.pem:/etc/ssl/gateway-private.pem
        ports:
            - 8000:80
            - 8002:443
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - 5432:5432
    s3:
        image: localstack/localstack:latest
        container_name: s3
        environment: 
            - AWS_DEFAULT_REGION=eu-west-1
            - EDGE_PORT=4566
            - SERVICES=s3
        ports: 
            - '4566-4583:4566-4583'
        volumes: 
            - .localstack:/tmp/localstack